ThULB/ThUniBib

jena/src/setup/classifications/ORIGIN.xml
Philosophische Fakultät
Fakultät für Sozial- und Verhaltenswissenschaften
Fakultät für Mathematik und Informatik
Physikalisch-Astronomische Fakultät
Chemisch-Geowissenschaftliche Fakultät
Fakultät für Biowissenschaften
Wissenschaftliche Zentren
=> Rechtswissenschaftliche Fakultaet

jena/src/setup/classifications/ORIGIN.xml
[#41] Updated 1060 to 'Zentrale Universitätsverwaltung'
[#41] Replaced ..wissenschaften with ..wissenschaft
[#41] Changed order of entries
[#41] Removed 'Sonstige/Externe'
[#41] Removed 'Didaktik'
=> [#41] Updated origin.xml

common/src/main/java/de/uni_jena/thunibib/ThUniBibCommands.java
[#54] Update core and optimize
=> [#54] Added command 'thunibib update solr project core'

common/src/main/resources/META-INF/resources/edit-admin.xed, common/src/main/resources/META-INF/resources/edit-publication.xed, common/src/main/resources/META-INF/resources/import-editor.xed, common/src/main/resources/META-INF/resources/import-genres.xed, common/src/main/resources/META-INF/resources/import-thunibib.xed, common/src/main/resources/META-INF/resources/newPublication.xed, common/src/main/resources/config/thunibib-common/messages_de.properties, common/src/main/resources/config/thunibib-common/messages_en.properties
…in.xed
[#65] Removed blanks before colon
=> [#65]  Applied changes in editors

common/pom.xml, common/src/main/java/de/uni_jena/thunibib/ThUniBibMailer.java, common/src/main/java/de/uni_jena/thunibib/enrichment/CommandTracker.java, common/src/main/java/de/uni_jena/thunibib/enrichment/EnrichmentByAffiliationCommands.java
* Added ImportTracker
* Added ThUniBibMailer
=> [#226] Send e-mail after import from catalog

common/src/main/resources/xsl/pica2mods_thunibib.xsl
=> [#254] add new template for origin and destatis category

ilmenau/src/setup/classifications/ORIGIN.xml
Addition of the labels "x-from" and "x-to"!
Expansion by further structural units!
=> Update ORIGIN.xml 27.01.2023

erfurt/src/main/resources/xsl/html-layout.xsl
https://mycore.atlassian.net/browse/UBO-226
=> [#284] Link to search result when possible

common/src/main/resources/META-INF/resources/import-editor.xed, common/src/main/resources/META-INF/resources/search.xed
=> Supply title in relatedItem search form

common/src/main/resources/xsl/import/thunibib-scopus2mods-common.xsl
=> Set affiliation with respect to author-group

ilmenau/src/main/resources/META-INF/resources/accessibility.xml
Replace <section> with <article> and adjust <div> classes.
=> Corrected Styles

ilmenau/src/main/resources/META-INF/resources/accessibility.xml
Replace <section> with <article> and adjust <div> classes. #333
=> Apply external changes to accessibility.xml [Ilmenau] #333

common/src/main/resources/config/thunibib-common/messages_de.properties, common/src/main/resources/config/thunibib-common/messages_en.properties
https://github.com/MyCoRe-Org/ubo/pull/278
=> UBO-238 Added/altered i18n keys

common/src/main/resources/META-INF/resources/newPublication.xed, common/src/main/resources/xsl/import/dbt2mods.xsl, erfurt/src/main/resources/META-INF/resources/newPublication.xed, ilmenau/src/main/resources/META-INF/resources/newPublication.xed
Import itself is currently not working due to errors in dbt2mods.xsl
=> #344 Enable import by dbt id via newPublication.xed

common/src/main/resources/config/thunibib-common/mycore.properties
needs https://github.com/MyCoRe-Org/ubo/pull/286
=> #343 Set property UBO.Export.Status.Restriction = +(status:confirmed status:unchecked)

common/src/main/resources/config/thunibib-common/mycore.properties
https://github.com/MyCoRe-Org/ubo/pull/290
=> #336 Set property MCR.IdentityPicker.strategy.Local.PID.Filter.enabled=false

common/src/main/resources/config/thunibib-common/mycore.properties
requires https://github.com/MyCoRe-Org/ubo/pull/310
=> FSU40THUL-1218 #411 Erweiterung CSV-Export

erfurt/src/main/resources/META-INF/resources/faq.xml, erfurt/src/main/resources/META-INF/resources/scss/base/_general.scss, ilmenau/src/main/resources/META-INF/resources/faq.xml, ilmenau/src/main/resources/xsl/html-layout.xsl, jena/src/main/resources/META-INF/resources/faq.xml, weimar/src/main/resources/META-INF/resources/scss/base/_general.scss
- fix heading in faq
- adjust facet size for erfurt and weimar layout
=> minor layout improvements:

common/src/main/java/de/uni_jena/thunibib/ThUniBibCommands.java, jena/src/main/resources/META-INF/resources/xeditor-custom.xed
see https://github.com/MyCoRe-Org/ubo/pull/321
=> FSU040THUL-972 Allow to set multiple fundings during import, made fundingType repeatable in form

common/src/main/java/de/uni_jena/thunibib/ThUniBibCommands.java, common/src/main/java/de/uni_jena/thunibib/matcher/ThUniBibMatcherLDAP.java
requires https://github.com/MyCoRe-Org/ubo/pull/343
=> #480 Added class ThUniBibMatcherLDAP

ilmenau/src/main/resources/META-INF/resources/faq.xml
Updating and completion of the English content
=> #487 Update faq.xml (Ilmenau)

ilmenau/src/setup/classifications/ORIGIN.xml
=> #503 Update ORIGIN.xml

weimar/src/setup/classifications/ORIGIN.xml
Großes Update viele Änderungen Stand: 12.03.2024
=> Update ORIGIN.xml (Weimar)

common/src/main/resources/META-INF/resources/import-editor.xed, common/src/main/resources/xsl/import/thunibib-scopus2mods-common.xsl, common/src/main/resources/xsl/mycoreobject2xMetaDissPlus.xsl, common/src/main/resources/xsl/pica2mods_thunibib-common.xsl, common/src/main/resources/xsl/thunibib-mods-filter-supported.xsl
requires https://github.com/MyCoRe-Org/ubo/pull/375
=> FSU040THUL-292 #529 Adopted template <xed:template id="languages"/> to rfc5646

common/src/main/resources/xsl/import/dbt2mods.xsl, common/src/main/resources/xsl/import/thunibib-genre2genre.xsl, common/src/main/resources/xsl/thunibib-mods-filter-supported.xsl, erfurt/src/main/resources/xsl/pica2mods_thunibib.xsl, ilmenau/src/main/resources/xsl/pica2mods_thunibib.xsl, jena-thulb/src/main/resources/xsl/pica2mods_thunibib.xsl, jena/src/main/resources/xsl/pica2mods_thunibib.xsl, weimar/src/main/resources/xsl/pica2mods_thunibib.xsl
needs https://github.com/MyCoRe-Org/ubo/pull/342
=> #478 Reflect changes of mods:genre handling in base UBO

common/src/main/java/de/uni_jena/thunibib/user/ThUniBibUtils.java, common/src/main/resources/config/thunibib-common/mycore.properties, common/src/main/resources/setup/classifications/orcidWorkType.xml, common/src/main/resources/setup/classifications/ubogenre.xml, common/src/main/resources/xsl/orcid2/v3/mcr2work.xsl, common/src/main/resources/xsl/orcid2/v3/work2mcr.xsl, jena/src/main/resources/config/thunibib-jena/mycore.properties
requires https://github.com/MyCoRe-Org/ubo/pull/342
=> #462 Enable genre mapping mapping to/from orcid

common/src/main/java/de/uni_jena/thunibib/impex/importer/DBTIdentifiers2MODSCollection.java, common/src/main/resources/META-INF/resources/import-editor.xed, common/src/main/resources/META-INF/resources/newPublication.xed, common/src/main/resources/config/thunibib-common/mycore.properties, common/src/main/resources/setup/classifications/importSourceType.xml, common/src/main/resources/xsl/import/dbt2mods-genre2uri.xsl, common/src/main/resources/xsl/import/dbt2mods.xsl, common/src/main/resources/xsl/thunibib-mods-filter-supported.xsl, erfurt/src/main/resources/META-INF/resources/newPublication.xed, ilmenau/src/main/resources/META-INF/resources/newPublication.xed
requires https://github.com/MyCoRe-Org/ubo/pull/383
=> #541 Improve import from DBT

ilmenau/src/main/resources/META-INF/resources/navigation.xml
=> Update 05.07.2024 navigation.xml

ilmenau/src/main/resources/META-INF/resources/newPublication.xed
Consolidation of terms and statements
=> Update 05.07.2024 newPublication.xed

common/src/main/resources/tu-ilm.csl
Letzte Anpassung des CSL Styles. Vorbereitung für die Produktivsetzung
=> Finale Änderung tu-ilm.csl

common/src/main/resources/META-INF/resources/edit-admin.xed, common/src/main/resources/META-INF/resources/edit-publication.xed, common/src/main/resources/META-INF/resources/import-editor.xed
see https://github.com/MyCoRe-Org/ubo/pull/408
=> FSU040THUL-3958 #584 Improved language select

ilmenau/src/main/resources/META-INF/resources/index.xed
#591 Correction to members and affiliates of the university
=> #591 Update index.xed (#590)

ilmenau/src/main/resources/META-INF/resources/faq.xml
Information on the note "Part of statistic" added and Gender-specific adaptations
=> Update 08.08.2024 faq.xml

common/src/main/java/de/uni_jena/thunibib/ThUniBibCommands.java, common/src/main/java/de/uni_jena/thunibib/impex/EnrichmentByAffiliationCommands.java, common/src/main/java/de/uni_jena/thunibib/impex/ThUniBibImportJobAction.java, common/src/main/resources/META-INF/resources/statistics.xml, common/src/main/resources/config/thunibib-common/mycore.properties, common/src/main/resources/xslt/mycoreobject-mods-detailed.xsl, jena-thulb/src/main/java/org/mycore/ubo/enrichment/EnrichmentCommands.java, pom.xml
https://github.com/MyCoRe-Org/ubo/pull/335
=> #464 Migrate to MyCoRe 2023.06.x

common/src/main/resources/tu-ilm.csl
2 Änderungen am CSL für eine bessere Darstellung
=> #621 Updated csl style for Ilmenau

ilmenau/src/setup/classifications/ORIGIN.xml
Vervollständigung und Aktualisierung
=> #637 Update ORIGIN.xml (Ilmenau)(#636)

common/src/main/resources/config/thunibib-common/messages_de.properties, common/src/main/resources/config/thunibib-common/messages_en.properties, erfurt/src/main/resources/META-INF/resources/scss/base/_general.scss, ilmenau/src/main/resources/META-INF/resources/scss/base/_general.scss, jena-thulb/src/main/resources/META-INF/resources/scss/base/_general.scss, jena/src/main/resources/META-INF/resources/scss/base/_general.scss, weimar/src/main/resources/META-INF/resources/scss/base/_general.scss
requires https://github.com/MyCoRe-Org/ubo/pull/429
=> FSU040THUL-5159 #641 Hide person_ths option in import-search.xed

common/src/main/resources/META-INF/resources/search.xed, common/src/main/resources/xsl/thunibib-mods-filter-supported.xsl
requires https://github.com/MyCoRe-Org/pica2mods/pull/111
=> FSU040THUL-5245 #643 Retain identfiers of type 'hdl' in thunibib-mods-filter-supported.xsl

common/src/main/resources/META-INF/resources/statistics.xml, common/src/main/resources/config/thunibib-common/messages_de.properties, common/src/main/resources/config/thunibib-common/messages_en.properties, common/src/main/resources/config/thunibib-common/solr/main/solr-config.json, common/src/main/resources/xsl/statistics.xsl
requires https://github.com/MyCoRe-Org/ubo/pull/432
=> #614 Updated solr request handlers to reflect recent changes due to migration from fachreferate to destatis classification

common/src/main/java/de/uni_jena/thunibib/common/events/ThUniBibAffiliationEventHandler.java, common/src/main/resources/META-INF/resources/import-editor.xed, common/src/main/resources/config/thunibib-common/messages_de.properties, common/src/main/resources/config/thunibib-common/messages_en.properties, common/src/main/resources/config/thunibib-common/mycore.properties, common/src/main/resources/setup/classifications/isAffiliated.xml, common/src/main/resources/xsl/thunibib-mods-postprocessor.xsl, common/src/main/resources/xsl/thunibib-mods-preprocessor.xsl
https://github.com/MyCoRe-Org/ubo/pull/435
=> FSU040THUL-5393 #650 Allow to indicate actual affiliation of author at time of publication

ilmenau/src/setup/classifications/ORIGIN.xml
Corrections and addition of new structural units
=> #686 Update ORIGIN.xml (Ilmenau)

ilmenau/src/setup/classifications/ORIGIN.xml
Corrections and addition of new structural units
=> #686 Update ORIGIN.xml (Ilmenau) (#685)

common/src/main/java/de/uni_jena/thunibib/impex/EnrichmentByAffiliationCommands.java, common/src/main/java/de/uni_jena/thunibib/impex/ThUniBibCatalogImportIdProvider.java, common/src/main/java/de/uni_jena/thunibib/impex/ThUniBibScopusImportIdProvider.java, common/src/main/resources/META-INF/resources/robots.txt, common/src/main/resources/config/thunibib-common/mycore.properties, common/src/main/resources/config/thunibib-common/solr/main/solr-config.json, common/src/main/resources/xsl/migration/xslt-migrate-importID.xsl
requires https://github.com/MyCoRe-Org/ubo/pull/467
=> #700 Added classes ThUniBibCatalogImportIdProvider and ThUniBibScopusImportIdProvider

ilmenau/src/setup/classifications/ORIGIN.xml
Adding a new Department and minor corrections
=> #715 Update ORIGIN.xml (Ilmenau)

ilmenau/src/setup/classifications/ORIGIN.xml
Adding a new Department and minor corrections
=> #715 Update ORIGIN.xml (Ilmenau) #714

common/src/main/java/de/uni_jena/thunibib/DBTImportCommands.java, common/src/main/java/de/uni_jena/thunibib/ThUniBibCommands.java, common/src/main/java/de/uni_jena/thunibib/Utilities.java, common/src/main/java/de/uni_jena/thunibib/impex/DBTImportIdProvider.java, common/src/main/java/de/uni_jena/thunibib/impex/importer/ConfigurableListImportJob.java, common/src/main/resources/config/thunibib-common/mycore.properties, common/src/main/resources/config/thunibib-common/solr/main/solr-schema.json, common/src/main/resources/xsl/thunibib-solr.xsl, erfurt/src/main/resources/config/thunibib-erfurt/mycore.properties, ilmenau/src/main/resources/config/thunibib-ilmenau/mycore.properties, jena/src/main/resources/config/thunibib-jena/mycore.properties, nordhausen/src/main/resources/config/thunibib-nordhausen/mycore.properties, weimar/src/main/resources/config/thunibib-weimar/mycore.properties
requires https://github.com/MyCoRe-Org/ubo/pull/470
=> #730 Add import from DBT

jena/src/setup/classifications/ORIGIN.xml
=> Updated ORIGIN.xml (Jena)

pom.xml
https://github.com/MyCoRe-Org/ubo/pull/490
=> #785 Upgrade to MyCoRe 2023.06.4 Snapshot
